server:
  port: 14000

spring:
  cloud:
    nacos:
      discovery:
        service: ad-serv
        serverAddr: 10.211.55.3:8848 #nacos地址
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 #sentinel地址
  datasource:
    url: jdbc:mysql://10.211.55.3:3306/ali_cloud_study
    username: root
    password: 123456
  redis:
    host: 10.211.55.3
    port: 6379

canal:
  server: 10.211.55.3:11111
  destination: example

